INSERT INTO `user` (`name`,`email`,`password`) VALUES ("Murphy","non@Nam.org","4203");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Nathaniel","id.libero.Donec@gravida.co.uk","KUU53HQP9PH");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Josiah","egestas.a.scelerisque@aliquetlibero.edu","CQU11BHM1RA");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Valentine","nec@Aliquam.edu","SKW58TCZ4XW");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Holmes","mi.Duis@egetmagnaSuspendisse.edu","YJD16XKK0HN");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Akeem","Mauris@tellus.net","EBX84KOP3UW");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Hayden","lacus@interdum.co.uk","YFF13ARH4TO");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Jamal","eu.tempor.erat@ullamcorpernislarcu.edu","NEK94KBM5KX");
INSERT INTO `User` (`name`,`email`,`password`) VALUES ("Burke","adipiscing.non.luctus@augue.com","XEA40SVE3UG");